#version 430 core

layout(local_size_x = 32, local_size_y = 32) in;
layout(rgba32f, binding = 0) uniform image2D hdr;

uniform float threshold;

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec3 color = imageLoad(hdr, texelCoord).xyz;
    float brightness = dot(color, vec3(0.2126, 0.7152, 0.0722)); // perceived brightness
    if (brightness <= threshold)
        imageStore(hdr, texelCoord, vec4(vec3(0), 1));
}